routeEnhancers:
    JobapplicationsDetailView:
        type: Extbase
        namespace: 'tx_jobapplications_detailview'
        routes:
            -   routePath: '/position/{slug}'
                _controller: 'Posting::show'
                _arguments:
                    slug: posting
        defaultController: 'Posting::list'
        defaults:
            page: ''
        aspects:
            slug:
                type: PersistedAliasMapper
                tableName: tx_jobapplications_domain_model_posting
                routeFieldName: slug
    JobapplicationsApplicationForm:
        type: Extbase
        namespace: 'tx_jobapplications_applicationform'
        routes:
            -   routePath: '/{slug}'
                _controller: 'Application::new'
                _arguments:
                    slug: posting
        defaultController: 'Application::new'
        defaults:
            page: ''
        aspects:
            slug:
                type: PersistedAliasMapper
                tableName: tx_jobapplications_domain_model_posting
                routeFieldName: slug